# Generated by Django 4.2.7 on 2024-02-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admin",
            field=models.BooleanField(
                blank=True, default="False", null=True, verbose_name="Admin"
            ),
        ),
    ]
