# Generated by Django 4.2.7 on 2024-01-09 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_user_alter_initialstudent_reg_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
