# Generated by Django 4.2.7 on 2024-01-09 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_user_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
