# Generated by Django 4.2.7 on 2024-01-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=10, unique=True, verbose_name='Registration Number')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_Date', models.DateField(verbose_name='Date of Birth')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.DeleteModel(
            name='initialStudent',
        ),
    ]
