# Generated by Django 4.2.7 on 2024-01-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_delete_initialstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_Date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
