# Generated by Django 4.2.7 on 2024-01-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birth_Date',
            new_name='birth_date',
        ),
    ]
