# Generated by Django 4.2.7 on 2024-01-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_rename_birth_date_student_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admin',
            field=models.BooleanField(blank=True, null=True, verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='student',
            name='auth_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Auth Code'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone'),
        ),
    ]
