# Generated by Django 4.2.7 on 2024-01-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_admin_student_auth_code_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admin',
            field=models.BooleanField(blank=True, default=False, verbose_name='Admin'),
        ),
    ]
