# Generated by Django 4.2.7 on 2024-01-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0011_student_nick_name_alter_student_admin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="nick_name",
        ),
        migrations.AlterField(
            model_name="student",
            name="admin",
            field=models.CharField(
                blank=True,
                default="False",
                max_length=20,
                null=True,
                verbose_name="Admin",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="auth_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Auth Code"
            ),
        ),
    ]
