# Generated by Django 4.2.7 on 2024-02-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("ECE 321", "ECE 321"),
                            ("FEG 303", "FEG 303"),
                            ("ELE 311", "ELE 311"),
                            ("ECE 323", "ECE 323"),
                            ("ELE 341", "ELE 341"),
                            ("ECE 331", "ECE 331"),
                            ("ELE 343", "ELE 343"),
                            ("ELE 353", "ELE 353"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
