# Generated by Django 4.2.7 on 2024-02-02 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_attendance_attendee"),
    ]

    operations = []
