# Generated by Django 4.2.7 on 2024-02-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0005_alter_attendance_day_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
