# Generated by Django 4.2.7 on 2024-02-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0006_attendance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
