# Generated by Django 4.2.7 on 2024-02-06 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0007_alter_attendance_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="date",
        ),
    ]
